name: shelf_keycloak
description: Keycloak middelware for shelf server.
version: 0.2.0
repository: https://github.com/pese-git/shelf_keycloak

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  logger: ^1.2.2
  oauth2: ^2.0.1
  shelf: ^1.4.0
#   path: ^1.8.0
  http: ^0.13.5
  jose: ^0.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
